### ISSUE TITLE
Add EN-AresManga 

### ISSUE THREAD

**Issue by yemenihandsome** [mohamedotaku/tachiyomi-extensions#2]
### Source information

EnAreasManga

### Source language

Arabic

### Source new URL

https://en-aresmanga.com/

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by mohamedotaku** [comment]
Hi, [yemenihandsome](https://github.com/yemenihandsome) i'm not the owner of tachiyomi extensions but if i have time i will try to add the source.
